spring:
  main:
    web-application-type: reactive
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  profiles:
    active: local
  application:
    name: api-gateway-server
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Clip Global Filter
            preLogger: true
            postLogger: true

---

# 로컬
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

service:
  user:
    url: http://localhost:8081
  auth:
    url: http://localhost:8082

auth:
  jwt:
    secret-key: U2VjcmV0S2V5UGFzc3dvcmQxMjM0NTY3ODkwMTIzNDU2Nzg5
    access-token-expiration-time: 3600 # 1시간
    refresh-token-expiration-time: 604800 # 7일


