server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: local
  application:
    name: api-gateway-server
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: SynergySpace Global Filter
            preLogger: true
            postLogger: true
      routes:
        # User Domain
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/user/api/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user(?<segment>/?.*), $\{segment}
        # 로그인
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/user/login
            - Method=POST
          filters:
            - AddRequestHeader=user-login, user-login-header
            - AddResponseHeader=